In [1]:
import numpy as np
import pandas as pd

scores = np.random.randint(50, 101, size=(50, 5))
df = pd.DataFrame(scores,
             columns = ["國文","英文","地理","人文","氣候"],
             index=[f"stu{i}" for i in range(1,51)]
)
df['國文']
df['英文']
df[['國文','地理']]
df

        國文   英文   地理   人文   氣候
stu1    77   96   68   84   94
stu2    59   67   95   55   59
stu3    95   99   84   70   51
stu4    87   71   62   88   92
stu5    82   98   76   83   50
stu6    71   93   71   58   93
stu7    74   69   58   65   93
stu8    70   57   52   79   78
stu9    51   57   53   80   77
stu10   60   75   66   73   54
stu11   70   81   86   99   55
stu12   63   93   76  100   99
stu13   78   97   79  100   74
stu14   88   71   91   50   69
stu15   93  100   82   69   53
stu16   79   76   54   91   72
stu17   93   68   65   79   90
stu18   54   59   55   77   57
stu19   55   58   76   88   64
stu20   62   81  100   96   89
stu21   52   83   82   81   99
stu22   79   88   98   99   81
stu23   74   52   84   55   94
stu24   70   60   51   72   60
stu25   98   61   98   79   65
stu26   57   87   87   57   77
stu27   64   60   97   73   90
stu28   52   94   58   90   84
stu29   98   82   56   83   67
stu30   86   61   65   75   84
stu31   60   65   96   84   91
stu32   65   91   80   62  100
stu33   54   97   62   56   92
stu34   89   98   52   93  100
stu35   91   67   92   86   99
stu36  100   94   92   83   94
stu37   87   76   70   63   86
stu38   81   67   81   94   57
stu39   98   95   86   51   98
stu40   66   80   79   60   99
stu41   53   67   96   78   85
stu42   91   79   56   87   60
stu43   80   51   91   70   75
stu44   76   90   65   68   57
stu45   63   72   62   96   63
stu46   97   85   67   95   88
stu47   91   85   85   66   92
stu48   84   61   61   50   89
stu49   71   99   68   79   63
stu50   60   84   84   72   89

In [2]:
df.loc['stu1']
df.loc[['stu1','stu50']]

       國文  英文  地理  人文  氣候
stu1   77  96  68  84  94
stu50  60  84  84  72  89